# Generated by Django 5.0.3 on 2024-03-14 06:44

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('code', models.CharField(max_length=8)),
                ('coords_lan', models.FloatField(blank=True, null=True)),
                ('coords_lon', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('area', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Wagon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=8)),
                ('owner', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='OperationLocationPoint',
            fields=[
                ('station_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rails.station')),
                ('operation', models.CharField(max_length=512)),
                ('operation_date', models.DateField()),
                ('update', models.DateField()),
            ],
            bases=('rails.station',),
        ),
        migrations.AddField(
            model_name='station',
            name='road',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rails.road'),
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(blank=True, choices=[('butan', 'BT'), ('propan', 'PT'), ('propan-butan', 'PBT'), ('butan-45', 'BT_45'), ('butan-75', 'BT_75')], max_length=20, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('loaded', models.BooleanField()),
                ('end', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='end', to='rails.station')),
                ('previous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rails.route')),
                ('start', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='start', to='rails.station')),
                ('wagon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rails.wagon')),
                ('locations', models.ManyToManyField(to='rails.operationlocationpoint')),
            ],
        ),
    ]
