# Generated by Django 5.0.3 on 2024-03-14 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='road',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rails.road'),
        ),
    ]
