# Generated by Django 5.0.3 on 2024-03-15 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rails', '0003_operationlocationpoint_source_alter_wagon_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
