# Generated by Django 5.0.3 on 2024-03-15 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rails', '0006_route_weight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='coords_lan',
            new_name='coords_lat',
        ),
    ]
