# Generated by Django 5.0.3 on 2024-03-15 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rails', '0007_rename_coords_lan_station_coords_lat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationlocationpoint',
            name='distances_left',
        ),
        migrations.AddField(
            model_name='station',
            name='distances_left',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
