# Generated by Django 5.0.3 on 2024-03-15 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rails', '0009_remove_route_locations_route_locations'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OperationLocationPoint',
        ),
    ]
