# Generated by Django 5.0.3 on 2024-03-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rails', '0010_delete_operationlocationpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='all_locations',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
