# Generated by Django 5.0.3 on 2024-03-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rails', '0011_route_all_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='loaded',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
