# Generated by Django 5.0.3 on 2024-03-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rails', '0012_alter_route_loaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='converted_locations',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
